version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    build: 
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - "./:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: "npm start"
