version: "3"

services:

### nginx ###############################################
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
    depends_on:
      - mysql
    volumes:
        # - /etc/nginx/conf.d:/etc/nginx/conf.d # 参考ページには記載があったがが正常に動作せずコメントアウト
        - /etc/letsencrypt:/etc/letsencrypt # 追記
        - /var/www/web:/var/www/web # 追記

### mysql ################################################
  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password

### node.js ###############################################
  web:
    build: 
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - "./:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: "npm start"

### certbot ################################################
  certbot:
      image: certbot/certbot:v1.7.0
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/www/web:/var/www/web
      command: ["--version"]