FROM node:latest

# ENV ENV MYSQL_DATABASE=${MYSQL_DATABASE} \
#     ENV MYSQL_HOST=${MYSQL_HOST} \
#     MYSQL_USER=${MYSQL_USER} \
#     MYSQL_PASSWORD=${MYSQL_PASSWORD}

WORKDIR /usr/src

COPY app/package*.json ./

RUN npm install

RUN npm install nodemon

COPY app .

EXPOSE 3000

# CMD [ "npm", "start" ]