# Base image
FROM nginx:latest

# Install Git
RUN apt-get update && apt-get install -y git

# Clone ar.js repository to /usr/share/nginx/html
RUN rm -rf /usr/share/nginx/html
WORKDIR /usr/share/nginx/web
# Delete all files in /usr/share/nginx/html
RUN git clone https://github.com/AR-js-org/AR.js.git .

#Make directores
WORKDIR /usr/share/nginx/web/static
COPY web/static/ /usr/share/nginx/web/static
WORKDIR /usr/share/nginx/web/src
COPY web/src /usr/share/nginx/web/src

# Remove default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy Nginx configuration file
COPY nginx/conf.d/default.conf /etc/nginx/conf.d/

# Expose port 80
EXPOSE 80
