FROM mysql:latest

# ENV MYSQL_DATABASE=${MYSQL_DATABASE} \
#     MYSQL_USER=${MYSQL_USER} \
#     MYSQL_PASSWORD=${MYSQL_PASSWORD} \
#     MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

# SQLダンプをコンテナにコピーする
COPY mysql/sql /docker-entrypoint-initdb.d/

# ↓ db接続コマンド
# mysql -u root -p